# Generated by Django 5.0.1 on 2024-02-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commander', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('etatLivraison', models.CharField(default='Expédiée', max_length=200)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='infoLivrason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('codePostal', models.CharField(max_length=200)),
                ('numTele', models.CharField(max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OurApp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Produitscommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, default=1, null=True)),
                ('date_ajouter', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OurApp.commande')),
                ('produits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OurApp.produit')),
            ],
        ),
    ]
