# Generated by Django 5.0.1 on 2024-02-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0002_commande_infolivrason_produitscommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etatLivraison',
            field=models.CharField(choices=[('Expédiée', 'Expédiée'), ('En Transit', 'En Transit'), ('Arrivée Locale', 'Arrivée Locale'), ('En Livraison', 'En Livraison'), ('Livrée', 'Livrée')], default='Expédiée', max_length=200),
        ),
        migrations.AlterField(
            model_name='produitscommande',
            name='quantite',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
